### ISSUE TITLE
Ngx-filter-pipe giving build error in Angular 4

### ISSUE THREAD

**Issue by achus-ui** [VadimDez/ngx-filter-pipe#53]
Am using angular-cli with version 1.6.8 and Angular with version 4.0.0. After the installation of ngx-filter-pipe, the ng build is giving the below mentioned error

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'C:\Harikrishnan_UI\VHealth\web\src'
resolve './$$_gendir/app/app.module.ngfactory' in 'C:\Harikrishnan_UI\VHealth\web\src'
  using description file: C:\Harikrishnan_UI\VHealth\web\package.json (relative path: ./src)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: C:\Harikrishnan_UI\VHealth\web\package.json (relative path: ./src)
    using description file: C:\Harikrishnan_UI\VHealth\web\package.json (relative path: ./src/$$_gendir/app/app.module.ngfactory)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        C:\Harikrishnan_UI\VHealth\web\src\$$_gendir\app\app.module.ngfactory doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        C:\Harikrishnan_UI\VHealth\web\src\$$_gendir\app\app.module.ngfactory.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        C:\Harikrishnan_UI\VHealth\web\src\$$_gendir\app\app.module.ngfactory.js doesn't exist
      as directory
        C:\Harikrishnan_UI\VHealth\web\src\$$_gendir\app\app.module.ngfactory doesn't exist
[C:\Harikrishnan_UI\VHealth\web\src\$$_gendir\app\app.module.ngfactory]
[C:\Harikrishnan_UI\VHealth\web\src\$$_gendir\app\app.module.ngfactory.ts]
[C:\Harikrishnan_UI\VHealth\web\src\$$_gendir\app\app.module.ngfactory.js]
[C:\Harikrishnan_UI\VHealth\web\src\$$_gendir\app\app.module.ngfactory]
 @ ./src/main.ts 3:0-74
 @ multi ./src/main.ts
ERROR in Error: Metadata version mismatch for module C:/Harikrishnan_UI/VHealth/web/node_modules/ngx-filter-pipe/ngx-filter-pipe.d.ts, found version 4, expected 3
    at StaticSymbolResolver.getModuleMetadata (C:\Harikrishnan_UI\VHealth\web\node_modules\@angular\compiler\bundles\compiler.umd.js:25616:34)
    at StaticSymbolResolver._createSymbolsOf (C:\Harikrishnan_UI\VHealth\web\node_modules\@angular\compiler\bundles\compiler.umd.js:25404:46)
    at StaticSymbolResolver.getSymbolsOf (C:\Harikrishnan_UI\VHealth\web\node_modules\@angular\compiler\bundles\compiler.umd.js:25385:14)
    at C:\Harikrishnan_UI\VHealth\web\node_modules\@angular\compiler\bundles\compiler.umd.js:24241:30
    at Array.forEach (<anonymous>)
    at extractProgramSymbols (C:\Harikrishnan_UI\VHealth\web\node_modules\@angular\compiler\bundles\compiler.umd.js:24240:79)
    at AotCompiler.analyzeModulesAsync (C:\Harikrishnan_UI\VHealth\web\node_modules\@angular\compiler\bundles\compiler.umd.js:23796:47)
    at CodeGenerator.codegen (C:\Harikrishnan_UI\VHealth\web\node_modules\@angular\compiler-cli\src\codegen.js:32:14)
    at Function.NgTools_InternalApi_NG_2.codeGen (C:\Harikrishnan_UI\VHealth\web\node_modules\@angular\compiler-cli\src\ngtools_api.js:73:30)
    at _donePromise.Promise.resolve.then (C:\Harikrishnan_UI\VHealth\web\node_modules\@ngtools\webpack\src\plugin.js:428:58)
    at <anonymous>

**Comment by VadimDez** [comment]
what version of `ngx-filter-pipe` are you using?

**Comment by achus-ui** [comment]
Installed the latest version of ngx-filter-pipe(2.0.0)

**Comment by VadimDez** [comment]
Since you're using angular 4 could you try to install `1.0.2` and give me feedback if it gives you same error?
